# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestReactNative

  target 'TestReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestReactNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestReactNative-tvOS

  target 'TestReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
